/**
 * Catálogo de Estilos de Cerveja — BJCP 2021
 * Faixas oficiais para validação e gauges visuais
 */

export interface BjcpStyle {
  id: string;
  code: string;
  name: string;
  category: string;
  ogMin: number;
  ogMax: number;
  fgMin: number;
  fgMax: number;
  ibuMin: number;
  ibuMax: number;
  abvMin: number;
  abvMax: number;
  ebcMin: number;
  ebcMax: number;
  description?: string;
}

export const BJCP_STYLES: BjcpStyle[] = [
  {
    id: '1a-american-light-lager',
    code: '1A',
    name: 'American Light Lager',
    category: 'Standard American Beer',
    ogMin: 1.028,
    ogMax: 1.040,
    fgMin: 0.998,
    fgMax: 1.008,
    ibuMin: 8,
    ibuMax: 12,
    abvMin: 2.8,
    abvMax: 4.2,
    ebcMin: 4,
    ebcMax: 6,
  },
  {
    id: '1b-american-lager',
    code: '1B',
    name: 'American Lager',
    category: 'Standard American Beer',
    ogMin: 1.040,
    ogMax: 1.050,
    fgMin: 1.004,
    fgMax: 1.010,
    ibuMin: 8,
    ibuMax: 18,
    abvMin: 4.2,
    abvMax: 5.3,
    ebcMin: 4,
    ebcMax: 8,
  },
  {
    id: '4a-munich-helles',
    code: '4A',
    name: 'Munich Helles',
    category: 'Pale Malty European Lager',
    ogMin: 1.044,
    ogMax: 1.048,
    fgMin: 1.006,
    fgMax: 1.012,
    ibuMin: 16,
    ibuMax: 22,
    abvMin: 4.7,
    abvMax: 5.4,
    ebcMin: 6,
    ebcMax: 10,
  },
  {
    id: '5a-german-leichtbier',
    code: '5A',
    name: 'German Leichtbier',
    category: 'Pale Bitter European Beer',
    ogMin: 1.026,
    ogMax: 1.034,
    fgMin: 1.006,
    fgMax: 1.010,
    ibuMin: 15,
    ibuMax: 28,
    abvMin: 2.5,
    abvMax: 3.6,
    ebcMin: 4,
    ebcMax: 8,
  },
  {
    id: '5d-german-pils',
    code: '5D',
    name: 'German Pils',
    category: 'Pale Bitter European Beer',
    ogMin: 1.044,
    ogMax: 1.050,
    fgMin: 1.008,
    fgMax: 1.013,
    ibuMin: 22,
    ibuMax: 40,
    abvMin: 4.4,
    abvMax: 5.2,
    ebcMin: 4,
    ebcMax: 8,
  },
  {
    id: '3b-bohemian-pilsener',
    code: '3B',
    name: 'Czech Premium Pale Lager (Bohemian Pilsener)',
    category: 'Czech Lager',
    ogMin: 1.044,
    ogMax: 1.060,
    fgMin: 1.013,
    fgMax: 1.017,
    ibuMin: 30,
    ibuMax: 45,
    abvMin: 4.2,
    abvMax: 5.8,
    ebcMin: 7,
    ebcMax: 12,
  },
  {
    id: '10a-weissbier',
    code: '10A',
    name: 'Weissbier (Hefeweizen)',
    category: 'German Wheat Beer',
    ogMin: 1.044,
    ogMax: 1.052,
    fgMin: 1.010,
    fgMax: 1.014,
    ibuMin: 8,
    ibuMax: 15,
    abvMin: 4.3,
    abvMax: 5.6,
    ebcMin: 4,
    ebcMax: 12,
  },
  {
    id: '24a-witbier',
    code: '24A',
    name: 'Witbier',
    category: 'Belgian Ale',
    ogMin: 1.044,
    ogMax: 1.052,
    fgMin: 1.008,
    fgMax: 1.012,
    ibuMin: 8,
    ibuMax: 20,
    abvMin: 4.5,
    abvMax: 5.5,
    ebcMin: 4,
    ebcMax: 8,
  },
  {
    id: '18a-blonde-ale',
    code: '18A',
    name: 'Blonde Ale',
    category: 'Pale American Beer',
    ogMin: 1.038,
    ogMax: 1.054,
    fgMin: 1.008,
    fgMax: 1.013,
    ibuMin: 15,
    ibuMax: 28,
    abvMin: 3.8,
    abvMax: 5.5,
    ebcMin: 6,
    ebcMax: 12,
  },
  {
    id: '18b-american-pale-ale',
    code: '18B',
    name: 'American Pale Ale (APA)',
    category: 'Pale American Beer',
    ogMin: 1.045,
    ogMax: 1.060,
    fgMin: 1.010,
    fgMax: 1.015,
    ibuMin: 30,
    ibuMax: 50,
    abvMin: 4.5,
    abvMax: 6.2,
    ebcMin: 10,
    ebcMax: 20,
  },
  {
    id: '21a-american-ipa',
    code: '21A',
    name: 'American IPA',
    category: 'IPA',
    ogMin: 1.056,
    ogMax: 1.070,
    fgMin: 1.008,
    fgMax: 1.014,
    ibuMin: 40,
    ibuMax: 70,
    abvMin: 5.5,
    abvMax: 7.5,
    ebcMin: 12,
    ebcMax: 28,
  },
  {
    id: '21b-hazy-ipa',
    code: '21B',
    name: 'Hazy / New England IPA (NEIPA)',
    category: 'IPA',
    ogMin: 1.060,
    ogMax: 1.085,
    fgMin: 1.010,
    fgMax: 1.018,
    ibuMin: 25,
    ibuMax: 60,
    abvMin: 6.0,
    abvMax: 8.5,
    ebcMin: 6,
    ebcMax: 14,
  },
  {
    id: '22a-double-ipa',
    code: '22A',
    name: 'Double IPA (Imperial IPA)',
    category: 'Strong American Ale',
    ogMin: 1.065,
    ogMax: 1.085,
    fgMin: 1.008,
    fgMax: 1.018,
    ibuMin: 60,
    ibuMax: 100,
    abvMin: 7.5,
    abvMax: 10.0,
    ebcMin: 12,
    ebcMax: 28,
  },
  {
    id: '12c-english-ipa',
    code: '12C',
    name: 'English IPA',
    category: 'Commonwealth Beer',
    ogMin: 1.050,
    ogMax: 1.075,
    fgMin: 1.010,
    fgMax: 1.018,
    ibuMin: 40,
    ibuMax: 60,
    abvMin: 5.0,
    abvMax: 7.5,
    ebcMin: 12,
    ebcMax: 28,
  },
  {
    id: '21b-session-ipa',
    code: '21B-S',
    name: 'Session IPA',
    category: 'Specialty IPA',
    ogMin: 1.038,
    ogMax: 1.052,
    fgMin: 1.008,
    fgMax: 1.014,
    ibuMin: 30,
    ibuMax: 50,
    abvMin: 3.5,
    abvMax: 5.0,
    ebcMin: 8,
    ebcMax: 18,
  },
  {
    id: '13a-dark-mild',
    code: '13A',
    name: 'Dark Mild',
    category: 'Brown British Beer',
    ogMin: 1.030,
    ogMax: 1.038,
    fgMin: 1.008,
    fgMax: 1.013,
    ibuMin: 10,
    ibuMax: 25,
    abvMin: 3.0,
    abvMax: 3.8,
    ebcMin: 28,
    ebcMax: 50,
  },
  {
    id: '13c-english-porter',
    code: '13C',
    name: 'English Porter',
    category: 'Brown British Beer',
    ogMin: 1.040,
    ogMax: 1.052,
    fgMin: 1.008,
    fgMax: 1.014,
    ibuMin: 18,
    ibuMax: 35,
    abvMin: 4.0,
    abvMax: 5.4,
    ebcMin: 40,
    ebcMax: 60,
  },
  {
    id: '15b-irish-stout',
    code: '15B',
    name: 'Irish Stout (Dry Stout)',
    category: 'Irish Beer',
    ogMin: 1.036,
    ogMax: 1.044,
    fgMin: 1.007,
    fgMax: 1.011,
    ibuMin: 25,
    ibuMax: 45,
    abvMin: 4.0,
    abvMax: 4.5,
    ebcMin: 50,
    ebcMax: 80,
  },
  {
    id: '16a-sweet-stout',
    code: '16A',
    name: 'Sweet Stout (Milk Stout)',
    category: 'Dark British Beer',
    ogMin: 1.044,
    ogMax: 1.060,
    fgMin: 1.012,
    fgMax: 1.024,
    ibuMin: 20,
    ibuMax: 40,
    abvMin: 4.0,
    abvMax: 6.0,
    ebcMin: 60,
    ebcMax: 80,
  },
  {
    id: '20c-imperial-stout',
    code: '20C',
    name: 'Imperial Stout (Russian Imperial)',
    category: 'American Porter and Stout',
    ogMin: 1.075,
    ogMax: 1.115,
    fgMin: 1.018,
    fgMax: 1.030,
    ibuMin: 50,
    ibuMax: 90,
    abvMin: 8.0,
    abvMax: 12.0,
    ebcMin: 60,
    ebcMax: 80,
  },
  {
    id: '25b-saison',
    code: '25B',
    name: 'Saison',
    category: 'Strong Belgian Ale',
    ogMin: 1.048,
    ogMax: 1.065,
    fgMin: 1.002,
    fgMax: 1.008,
    ibuMin: 20,
    ibuMax: 35,
    abvMin: 5.0,
    abvMax: 7.0,
    ebcMin: 8,
    ebcMax: 28,
  },
  {
    id: '26c-belgian-tripel',
    code: '26C',
    name: 'Belgian Tripel',
    category: 'Monastic Ale',
    ogMin: 1.075,
    ogMax: 1.085,
    fgMin: 1.008,
    fgMax: 1.014,
    ibuMin: 20,
    ibuMax: 40,
    abvMin: 7.5,
    abvMax: 9.5,
    ebcMin: 9,
    ebcMax: 14,
  },
  {
    id: '23a-berliner-weisse',
    code: '23A',
    name: 'Berliner Weisse',
    category: 'European Sour Ale',
    ogMin: 1.028,
    ogMax: 1.032,
    fgMin: 1.003,
    fgMax: 1.006,
    ibuMin: 3,
    ibuMax: 8,
    abvMin: 2.8,
    abvMax: 3.8,
    ebcMin: 4,
    ebcMax: 6,
  },
  {
    id: 'x1-catharina-sour',
    code: 'X1',
    name: 'Catharina Sour (Estilo Brasileiro)',
    category: 'Brazilian / Fruit Sour',
    ogMin: 1.036,
    ogMax: 1.048,
    fgMin: 1.004,
    fgMax: 1.008,
    ibuMin: 2,
    ibuMax: 8,
    abvMin: 3.4,
    abvMax: 5.0,
    ebcMin: 4,
    ebcMax: 12,
  },
];

export function findBjcpStyle(nameOrCode: string): BjcpStyle | undefined {
  if (!nameOrCode) return undefined;
  const lower = nameOrCode.toLowerCase().trim();
  return BJCP_STYLES.find(
    (s) =>
      s.code.toLowerCase() === lower ||
      s.name.toLowerCase().includes(lower) ||
      lower.includes(s.name.toLowerCase())
  );
}

/**
 * Retorna o status de conformidade da receita com o estilo BJCP (percentual e se está dentro).
 */
export function checkStyleCompliance(
  style: BjcpStyle,
  og: number,
  fg: number,
  ibu: number,
  abv: number,
  ebc: number
) {
  const isOgOk = og >= style.ogMin && og <= style.ogMax;
  const isFgOk = fg >= style.fgMin && fg <= style.fgMax;
  const isIbuOk = ibu >= style.ibuMin && ibu <= style.ibuMax;
  const isAbvOk = abv >= style.abvMin && abv <= style.abvMax;
  const isEbcOk = ebc >= style.ebcMin && ebc <= style.ebcMax;

  let matches = 0;
  if (isOgOk) matches++;
  if (isFgOk) matches++;
  if (isIbuOk) matches++;
  if (isAbvOk) matches++;
  if (isEbcOk) matches++;

  const scorePercent = Math.round((matches / 5) * 100);

  return {
    isOgOk,
    isFgOk,
    isIbuOk,
    isAbvOk,
    isEbcOk,
    scorePercent,
    overallMatch: scorePercent >= 80,
  };
}
